/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protocol.pb-c.h"
void   dkvs__row__init
                     (Dkvs__Row         *message)
{
  static Dkvs__Row init_value = DKVS__ROW__INIT;
  *message = init_value;
}
size_t dkvs__row__get_packed_size
                     (const Dkvs__Row *message)
{
  assert(message->base.descriptor == &dkvs__row__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dkvs__row__pack
                     (const Dkvs__Row *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dkvs__row__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dkvs__row__pack_to_buffer
                     (const Dkvs__Row *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dkvs__row__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dkvs__Row *
       dkvs__row__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dkvs__Row *)
     protobuf_c_message_unpack (&dkvs__row__descriptor,
                                allocator, len, data);
}
void   dkvs__row__free_unpacked
                     (Dkvs__Row *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dkvs__row__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dkvs__status__init
                     (Dkvs__Status         *message)
{
  static Dkvs__Status init_value = DKVS__STATUS__INIT;
  *message = init_value;
}
size_t dkvs__status__get_packed_size
                     (const Dkvs__Status *message)
{
  assert(message->base.descriptor == &dkvs__status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dkvs__status__pack
                     (const Dkvs__Status *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dkvs__status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dkvs__status__pack_to_buffer
                     (const Dkvs__Status *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dkvs__status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dkvs__Status *
       dkvs__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dkvs__Status *)
     protobuf_c_message_unpack (&dkvs__status__descriptor,
                                allocator, len, data);
}
void   dkvs__status__free_unpacked
                     (Dkvs__Status *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dkvs__status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dkvs__router_request__init
                     (Dkvs__RouterRequest         *message)
{
  static Dkvs__RouterRequest init_value = DKVS__ROUTER_REQUEST__INIT;
  *message = init_value;
}
size_t dkvs__router_request__get_packed_size
                     (const Dkvs__RouterRequest *message)
{
  assert(message->base.descriptor == &dkvs__router_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dkvs__router_request__pack
                     (const Dkvs__RouterRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dkvs__router_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dkvs__router_request__pack_to_buffer
                     (const Dkvs__RouterRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dkvs__router_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dkvs__RouterRequest *
       dkvs__router_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dkvs__RouterRequest *)
     protobuf_c_message_unpack (&dkvs__router_request__descriptor,
                                allocator, len, data);
}
void   dkvs__router_request__free_unpacked
                     (Dkvs__RouterRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dkvs__router_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dkvs__router_response__init
                     (Dkvs__RouterResponse         *message)
{
  static Dkvs__RouterResponse init_value = DKVS__ROUTER_RESPONSE__INIT;
  *message = init_value;
}
size_t dkvs__router_response__get_packed_size
                     (const Dkvs__RouterResponse *message)
{
  assert(message->base.descriptor == &dkvs__router_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dkvs__router_response__pack
                     (const Dkvs__RouterResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dkvs__router_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dkvs__router_response__pack_to_buffer
                     (const Dkvs__RouterResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dkvs__router_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dkvs__RouterResponse *
       dkvs__router_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dkvs__RouterResponse *)
     protobuf_c_message_unpack (&dkvs__router_response__descriptor,
                                allocator, len, data);
}
void   dkvs__router_response__free_unpacked
                     (Dkvs__RouterResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &dkvs__router_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dkvs__row__field_descriptors[4] =
{
  {
    "key_length",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Dkvs__Row, has_key_length),
    offsetof(Dkvs__Row, key_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_length",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Dkvs__Row, has_value_length),
    offsetof(Dkvs__Row, value_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dkvs__Row, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dkvs__Row, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dkvs__row__field_indices_by_name[] = {
  2,   /* field[2] = key */
  0,   /* field[0] = key_length */
  3,   /* field[3] = value */
  1,   /* field[1] = value_length */
};
static const ProtobufCIntRange dkvs__row__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dkvs__row__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dkvs.Row",
  "Row",
  "Dkvs__Row",
  "dkvs",
  sizeof(Dkvs__Row),
  4,
  dkvs__row__field_descriptors,
  dkvs__row__field_indices_by_name,
  1,  dkvs__row__number_ranges,
  (ProtobufCMessageInit) dkvs__row__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dkvs__status__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Dkvs__Status, status),
    &dkvs__status_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dkvs__status__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange dkvs__status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dkvs__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dkvs.Status",
  "Status",
  "Dkvs__Status",
  "dkvs",
  sizeof(Dkvs__Status),
  1,
  dkvs__status__field_descriptors,
  dkvs__status__field_indices_by_name,
  1,  dkvs__status__number_ranges,
  (ProtobufCMessageInit) dkvs__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dkvs__router_request__field_descriptors[2] =
{
  {
    "key_length",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Dkvs__RouterRequest, has_key_length),
    offsetof(Dkvs__RouterRequest, key_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dkvs__RouterRequest, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dkvs__router_request__field_indices_by_name[] = {
  1,   /* field[1] = key */
  0,   /* field[0] = key_length */
};
static const ProtobufCIntRange dkvs__router_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dkvs__router_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dkvs.RouterRequest",
  "RouterRequest",
  "Dkvs__RouterRequest",
  "dkvs",
  sizeof(Dkvs__RouterRequest),
  2,
  dkvs__router_request__field_descriptors,
  dkvs__router_request__field_indices_by_name,
  1,  dkvs__router_request__number_ranges,
  (ProtobufCMessageInit) dkvs__router_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dkvs__router_response__field_descriptors[1] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dkvs__RouterResponse, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dkvs__router_response__field_indices_by_name[] = {
  0,   /* field[0] = address */
};
static const ProtobufCIntRange dkvs__router_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dkvs__router_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dkvs.RouterResponse",
  "RouterResponse",
  "Dkvs__RouterResponse",
  "dkvs",
  sizeof(Dkvs__RouterResponse),
  1,
  dkvs__router_response__field_descriptors,
  dkvs__router_response__field_indices_by_name,
  1,  dkvs__router_response__number_ranges,
  (ProtobufCMessageInit) dkvs__router_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dkvs__status_type__enum_values_by_number[2] =
{
  { "OK", "DKVS__STATUS_TYPE__OK", 0 },
  { "ERROR", "DKVS__STATUS_TYPE__ERROR", 1 },
};
static const ProtobufCIntRange dkvs__status_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex dkvs__status_type__enum_values_by_name[2] =
{
  { "ERROR", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor dkvs__status_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dkvs.StatusType",
  "StatusType",
  "Dkvs__StatusType",
  "dkvs",
  2,
  dkvs__status_type__enum_values_by_number,
  2,
  dkvs__status_type__enum_values_by_name,
  1,
  dkvs__status_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCMethodDescriptor dkvs__router__method_descriptors[1] =
{
  { "GetServer", &dkvs__router_request__descriptor, &dkvs__router_response__descriptor },
};
const unsigned dkvs__router__method_indices_by_name[] = {
  0         /* GetServer */
};
const ProtobufCServiceDescriptor dkvs__router__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "dkvs.Router",
  "Router",
  "Dkvs__Router",
  "dkvs",
  1,
  dkvs__router__method_descriptors,
  dkvs__router__method_indices_by_name
};
void dkvs__router__get_server(ProtobufCService *service,
                              const Dkvs__RouterRequest *input,
                              Dkvs__RouterResponse_Closure closure,
                              void *closure_data)
{
  assert(service->descriptor == &dkvs__router__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void dkvs__router__init (Dkvs__Router_Service *service,
                         Dkvs__Router_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &dkvs__router__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
static const ProtobufCMethodDescriptor dkvs__server__method_descriptors[2] =
{
  { "Set", &dkvs__row__descriptor, &dkvs__status__descriptor },
  { "Get", &dkvs__router_request__descriptor, &dkvs__row__descriptor },
};
const unsigned dkvs__server__method_indices_by_name[] = {
  1,        /* Get */
  0         /* Set */
};
const ProtobufCServiceDescriptor dkvs__server__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "dkvs.Server",
  "Server",
  "Dkvs__Server",
  "dkvs",
  2,
  dkvs__server__method_descriptors,
  dkvs__server__method_indices_by_name
};
void dkvs__server__set(ProtobufCService *service,
                       const Dkvs__Row *input,
                       Dkvs__Status_Closure closure,
                       void *closure_data)
{
  assert(service->descriptor == &dkvs__server__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void dkvs__server__get(ProtobufCService *service,
                       const Dkvs__RouterRequest *input,
                       Dkvs__Row_Closure closure,
                       void *closure_data)
{
  assert(service->descriptor == &dkvs__server__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void dkvs__server__init (Dkvs__Server_Service *service,
                         Dkvs__Server_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &dkvs__server__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
